// SPDX-License-Identifier: MIT

//! Auto-generated Envoy dynamic module ABI bindings.
//!
//! Generated by `bindgen` from the vendored `abi/abi.h`.
//! To regenerate: `cargo build -p praxis-proxy-dynamic-modules --features regenerate-abi`

#![allow(
    clippy::allow_attributes_without_reason,
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    missing_docs,
    unreachable_pub,
    unused_imports,
    unused_qualifications,
    trivial_casts,
    trivial_numeric_casts,
    clippy::doc_markdown,
    clippy::indexing_slicing,
    clippy::missing_docs_in_private_items,
    clippy::unreadable_literal,
    clippy::cognitive_complexity,
    clippy::too_many_lines,
    clippy::large_types_passed_by_value,
    clippy::struct_excessive_bools,
    clippy::fn_params_excessive_bools,
    clippy::too_many_arguments,
    clippy::default_trait_access,
    clippy::used_underscore_binding,
    clippy::missing_safety_doc,
    clippy::undocumented_unsafe_blocks,
    clippy::ptr_as_ptr,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_lossless,
    clippy::unnecessary_wraps,
    clippy::doc_link_with_quotes,
    reason = "auto-generated FFI bindings"
)]

include!("abi_generated.rs");
